# ============================================================================
# monitoring/prometheus.yml - Prometheus Configuration
# ============================================================================
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'master-generators-monitor'

scrape_configs:
  # FastAPI metrics
  - job_name: 'fastapi'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics'
    
  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
      
  # PostgreSQL exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
      
  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
      
  # Nginx exporter
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

# Alert rules
rule_files:
  - '/etc/prometheus/alerts.yml'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
